# Generated by Django 5.1.7 on 2025-08-24 19:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_order', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('technician_name', models.CharField(max_length=150)),
                ('jwt_token', models.TextField()),
                ('jwt_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_use', 'En uso'), ('completed', 'Completada'), ('failed', 'Fallida'), ('expired', 'Expirada'), ('used', 'Usada')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
