# Generated by Django 5.1.7 on 2025-08-24 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='closing_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='closing_reason',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('foto_domicilio', 'Foto del domicilio'), ('doc_firmado', 'Documento firmado'), ('doc_identidad', 'Documento de identidad')], max_length=32)),
                ('file', models.FileField(upload_to='evidences/')),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='orders.serviceorder')),
            ],
        ),
    ]
