# Generated by Django 5.1.7 on 2025-09-02 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_serviceorder_closed_at_serviceorder_closing_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='ot_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='ot_token_jti',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('ot_token_copy', models.TextField()),
                ('ot_jti', models.CharField(max_length=64)),
                ('audit_jwt', models.TextField()),
                ('audit_jti', models.CharField(max_length=64)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='orders.serviceorder')),
            ],
        ),
    ]
